-- Generated by hypr2lua from hyprlang .conf
-- Hyprland Lua config (v0.55+)

-- This is a sample Hyprland config
-- Converted from hyprlang to lua

local mod = "SUPER"
local terminal = "kitty"
local fileManager = "dolphin"
local menu = "wofi --show drun"

-- Keybinds

-- Window rules

-- Workspace rules


hl.set {
    general = {
        gaps_in = 5,
        gaps_out = 20,
        border_size = 2,
        col = {
            active_border = "rgba(33ccffee) rgba(00ff99ee) 45deg",
            inactive_border = "rgba(595959aa)",
        },
        resize_on_border = false,
        allow_tearing = false,
        layout = "dwindle",
    },
    decoration = {
        rounding = 10,
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
        blur = {
            enabled = true,
            size = 3,
            passes = 1,
            vibrancy = 0.1696,
        },
    },
    animations = {
        enabled = "yes",
    },
    dwindle = {
        pseudotile = true,
        preserve_split = true,
    },
    gestures = {
        workspace_swipe = false,
    },
    misc = {
        force_default_wallpaper = -1,
        disable_hyprland_logo = false,
    },
    input = {
        kb_layout = "us",
        follow_mouse = 1,
        sensitivity = 0,
        touchpad = {
            natural_scroll = false,
        },
    },
}

hl.monitor("", "preferred", "auto", 1)
hl.bezier("easeOutQuint", 0.23, 1, 0.32, 1)
hl.bezier("easeInOutCubic", 0.65, 0.05, 0.36, 1)
hl.animation("global", 1, 10, "default")
hl.animation("border", 1, 5.39, "easeOutQuint")
hl.animation("windows", 1, 4.79, "easeOutQuint")
hl.animation("fade", 1, 7, "default")
hl.animation("workspaces", 1, 1.81, "easeOutQuint")
hl.bind("SUPER", "Q", "exec", "kitty")
hl.bind("SUPER", "C", "killactive")
hl.bind("SUPER", "M", "exit")
hl.bind("SUPER", "E", "exec", "dolphin")
hl.bind("SUPER", "V", "togglefloating")
hl.bind("SUPER", "R", "exec", "wofi --show drun")
hl.bind("SUPER", "P", "pseudo")
hl.bind("SUPER", "J", "togglesplit")
hl.bindl("SUPER", "escape", "exec", "loginctl lock-session")
hl.bindl("", "XF86AudioMute", "exec", "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle")
hl.bindm("SUPER", "mouse:272", "movewindow")
hl.bindm("SUPER", "mouse:273", "resizewindow")
hl.windowrulev2("suppressevent maximize", "class:.*")
hl.windowrulev2("float", "class:^(org.kde.dolphin)$")
hl.windowrulev2("size 800 600", "class:^(kitty)$")
hl.workspace(1, "monitor:DP-1")
hl.workspace(2, "monitor:HDMI-A-1")
hl.exec_once("waybar")
hl.exec_once("hyprpaper")
require("~/.config/hypr/colors")
