use crate::parser::Node;

pub fn generate(nodes: &[Node]) -> String {
    let mut out = String::new();
    out.push_str("-- Generated by hypr2lua from hyprlang .conf\n");
    out.push_str("-- Hyprland Lua config (v0.55+)\n\n");

    let mut set_entries: Vec<(String, LuaValue)> = Vec::new();
    let mut preamble_lines: Vec<String> = Vec::new();
    let mut postamble_lines: Vec<String> = Vec::new();

    for node in nodes {
        match node {
            Node::BlankLine => {
                preamble_lines.push(String::new());
            }
            Node::Comment(text) => {
                preamble_lines.push(format!("--{}", text));
            }
            Node::Variable { name, value } => {
                let lua_name = sanitize_var_name(name);
                let resolved = resolve_vars(value, nodes);
                let val = lua_value(&resolved);
                preamble_lines.push(format!("local {} = {}", lua_name, format_lua_value(&val)));
            }
            Node::Source { path } => {
                let resolved = resolve_vars(path, nodes);
                let lua_path = resolved.trim_end_matches(".conf").trim_end_matches(".lua");
                postamble_lines.push(format!("require({})", lua_string(lua_path)));
            }
            Node::Section { name, children } => {
                let (section_val, extracted_keywords) = build_section_table(children, nodes);
                set_entries.push((name.clone(), section_val));
                for kw_call in extracted_keywords {
                    postamble_lines.push(kw_call);
                }
            }
            Node::Assignment { key, value } => {
                if key == "autogenerated" {
                    continue;
                }
                let resolved = resolve_vars(value, nodes);
                if key.contains('.') {
                    let parts: Vec<&str> = key.splitn(2, '.').collect();
                    let section = parts[0].to_string();
                    let inner_key = parts[1].to_string();
                    if let Some(existing) = set_entries.iter_mut().find(|(k, _)| k == &section) {
                        if let LuaValue::Table(ref mut entries) = existing.1 {
                            entries.push((inner_key, lua_value(&resolved)));
                        }
                    } else {
                        set_entries.push((
                            section,
                            LuaValue::Table(vec![(inner_key, lua_value(&resolved))]),
                        ));
                    }
                } else {
                    set_entries.push((key.clone(), lua_value(&resolved)));
                }
            }
            Node::Bind { variant, args } => {
                let resolved_args: Vec<String> = args.iter().map(|a| resolve_vars(a, nodes)).collect();
                let call = format_bind(variant, &resolved_args);
                postamble_lines.push(call);
            }
            Node::Keyword { name, args } => {
                let resolved_args: Vec<String> = args.iter().map(|a| resolve_vars(a, nodes)).collect();
                let call = format_keyword(name, &resolved_args);
                postamble_lines.push(call);
            }
        }
    }

    let preamble = collapse_blank_lines(&preamble_lines);
    out.push_str(&preamble);

    if !set_entries.is_empty() {
        out.push_str("\nhl.set {\n");
        for (key, val) in &set_entries {
            write_table_entry(&mut out, key, val, 1);
        }
        out.push_str("}\n");
    }

    if !postamble_lines.is_empty() {
        out.push('\n');
        for line in &postamble_lines {
            out.push_str(line);
            out.push('\n');
        }
    }

    out
}

fn collapse_blank_lines(lines: &[String]) -> String {
    let mut result = String::new();
    let mut prev_blank = false;
    for line in lines {
        if line.is_empty() {
            if !prev_blank {
                result.push('\n');
            }
            prev_blank = true;
        } else {
            result.push_str(line);
            result.push('\n');
            prev_blank = false;
        }
    }
    result
}

#[derive(Debug, Clone)]
#[allow(dead_code)]
enum LuaValue {
    Str(String),
    Num(String),
    Bool(bool),
    Table(Vec<(String, LuaValue)>),
    Raw(String),
}

fn build_section_table(children: &[Node], all_nodes: &[Node]) -> (LuaValue, Vec<String>) {
    let mut entries: Vec<(String, LuaValue)> = Vec::new();
    let mut extracted_keywords: Vec<String> = Vec::new();

    for child in children {
        match child {
            Node::Assignment { key, value } => {
                let resolved = resolve_vars(value, all_nodes);
                if key.contains('.') {
                    let parts: Vec<&str> = key.splitn(2, '.').collect();
                    let section = parts[0].to_string();
                    let inner_key = parts[1].to_string();
                    if let Some(existing) = entries.iter_mut().find(|(k, _)| k == &section) {
                        if let LuaValue::Table(ref mut inner) = existing.1 {
                            inner.push((inner_key, lua_value(&resolved)));
                        }
                    } else {
                        entries.push((
                            section,
                            LuaValue::Table(vec![(inner_key, lua_value(&resolved))]),
                        ));
                    }
                } else {
                    entries.push((key.clone(), lua_value(&resolved)));
                }
            }
            Node::Section { name, children: grandchildren } => {
                let (sub, sub_keywords) = build_section_table(grandchildren, all_nodes);
                entries.push((name.clone(), sub));
                extracted_keywords.extend(sub_keywords);
            }
            Node::Keyword { name, args } => {
                let resolved_args: Vec<String> = args.iter().map(|a| resolve_vars(a, all_nodes)).collect();
                let call = format_keyword(name, &resolved_args);
                extracted_keywords.push(call);
            }
            Node::Comment(_) | Node::BlankLine => {}
            _ => {}
        }
    }

    (LuaValue::Table(entries), extracted_keywords)
}

fn lua_value(s: &str) -> LuaValue {
    let trimmed = s.trim();

    if trimmed == "true" {
        return LuaValue::Bool(true);
    }
    if trimmed == "false" {
        return LuaValue::Bool(false);
    }

    if trimmed.parse::<i64>().is_ok() || trimmed.parse::<f64>().is_ok() {
        return LuaValue::Num(trimmed.to_string());
    }

    if trimmed.starts_with("0x") && trimmed[2..].chars().all(|c| c.is_ascii_hexdigit()) {
        return LuaValue::Num(trimmed.to_string());
    }

    if trimmed.starts_with("rgba(") || trimmed.starts_with("rgb(") {
        return LuaValue::Str(trimmed.to_string());
    }

    LuaValue::Str(trimmed.to_string())
}

fn resolve_vars(value: &str, nodes: &[Node]) -> String {
    let mut result = value.to_string();
    for node in nodes {
        if let Node::Variable { name, value: var_val } = node {
            let pattern = format!("${}", name);
            if result.contains(&pattern) {
                result = result.replace(&pattern, var_val);
            }
        }
    }
    result
}

fn sanitize_var_name(name: &str) -> String {
    name.replace('-', "_").replace(' ', "_")
}

fn lua_string(s: &str) -> String {
    let escaped = s.replace('\\', "\\\\").replace('"', "\\\"");
    format!("\"{}\"", escaped)
}

fn format_lua_value(val: &LuaValue) -> String {
    match val {
        LuaValue::Str(s) => lua_string(s),
        LuaValue::Num(n) => n.clone(),
        LuaValue::Bool(b) => b.to_string(),
        LuaValue::Raw(r) => r.clone(),
        LuaValue::Table(entries) => {
            let mut s = String::from("{\n");
            for (k, v) in entries {
                s.push_str(&format!("    {} = {},\n", k, format_lua_value(v)));
            }
            s.push('}');
            s
        }
    }
}

fn format_bind(variant: &str, args: &[String]) -> String {
    let hl_fn = match variant {
        "bind" => "hl.bind",
        "bindl" => "hl.bindl",
        "bindm" => "hl.bindm",
        "bindr" => "hl.bindr",
        "bindle" => "hl.bindle",
        "bindlr" => "hl.bindlr",
        _ => "hl.bind",
    };

    let lua_args: Vec<String> = args.iter().map(|a| lua_string(a)).collect();
    format!("{}({})", hl_fn, lua_args.join(", "))
}

fn format_keyword(name: &str, args: &[String]) -> String {
    let hl_fn = match name {
        "exec-once" => "hl.exec_once",
        "exec" => "hl.exec",
        "windowrule" => "hl.windowrule",
        "windowrulev2" => "hl.windowrulev2",
        "workspace" => "hl.workspace",
        "monitor" => "hl.monitor",
        "bezier" => "hl.bezier",
        "animation" => "hl.animation",
        "layerrule" => "hl.layerrule",
        "plugin" => "hl.plugin",
        _ => return format!("-- unsupported keyword: {}", name),
    };

    let lua_args: Vec<String> = args.iter().map(|a| {
        if a.parse::<f64>().is_ok() {
            a.clone()
        } else {
            lua_string(a)
        }
    }).collect();
    format!("{}({})", hl_fn, lua_args.join(", "))
}

fn write_table_entry(out: &mut String, key: &str, val: &LuaValue, indent: usize) {
    let pad = "    ".repeat(indent);
    let safe_key = if needs_quoting(key) {
        format!("[\"{}\"]", key)
    } else {
        key.to_string()
    };

    match val {
        LuaValue::Table(entries) => {
            out.push_str(&format!("{}{} = {{\n", pad, safe_key));
            for (k, v) in entries {
                write_table_entry(out, k, v, indent + 1);
            }
            out.push_str(&format!("{}}},\n", pad));
        }
        LuaValue::Str(s) => {
            out.push_str(&format!("{}{} = {},\n", pad, safe_key, lua_string(s)));
        }
        LuaValue::Num(n) => {
            out.push_str(&format!("{}{} = {},\n", pad, safe_key, n));
        }
        LuaValue::Bool(b) => {
            out.push_str(&format!("{}{} = {},\n", pad, safe_key, b));
        }
        LuaValue::Raw(r) => {
            out.push_str(&format!("{}{} = {},\n", pad, safe_key, r));
        }
    }
}

fn needs_quoting(key: &str) -> bool {
    if key.is_empty() {
        return true;
    }
    let first = key.chars().next().unwrap();
    if first.is_ascii_digit() {
        return true;
    }
    key.contains('-') || key.contains(' ') || key.contains('.')
}
