//! Lua code generator for Hyprland configuration.
//!
//! This module converts a parsed hyprlang AST into Lua code compatible with
//! Hyprland v0.55+'s Lua configuration format.

use crate::parser::Node;

/// Generates Lua code from a parsed hyprlang AST.
///
/// The output is structured in three sections:
/// 1. **Preamble**: Comments, blank lines, and `local` variable declarations
/// 2. **`hl.set { ... }` block**: Configuration sections and key-value assignments
/// 3. **Postamble**: Function calls for binds, keywords, exec-once, source/requires
///
/// # Arguments
///
/// * `nodes` - The parsed AST nodes from [`crate::parser::parse`].
///
/// # Returns
///
/// A string containing the generated Lua code.
///
/// # Examples
///
/// ```
/// use hypr2lua::parser::parse;
/// use hypr2lua::lua_gen::generate;
///
/// let input = "general {\n    gaps_in = 5\n}";
/// let nodes = parse(input);
/// let lua = generate(&nodes);
/// assert!(lua.contains("hl.set"));
/// assert!(lua.contains("gaps_in = 5"));
/// ```
pub fn generate(nodes: &[Node]) -> String {
    let mut out = String::new();
    out.push_str("-- Generated by hypr2lua from hyprlang .conf\n");
    out.push_str("-- Hyprland Lua config (v0.55+)\n\n");

    let mut set_entries: Vec<(String, LuaValue)> = Vec::new();
    let mut preamble_lines: Vec<String> = Vec::new();
    let mut postamble_lines: Vec<String> = Vec::new();
    let mut source_entries: Vec<(String, bool)> = Vec::new();

    for node in nodes {
        match node {
            Node::BlankLine => {
                preamble_lines.push(String::new());
            }
            Node::Comment(text) => {
                preamble_lines.push(format!("--{}", text));
            }
            Node::Variable { name, value } => {
                let lua_name = sanitize_var_name(name);
                let resolved = resolve_vars(value, nodes);
                let val = lua_value(&resolved);
                preamble_lines.push(format!("local {} = {}", lua_name, format_lua_value(&val)));
            }
            Node::Source { path } => {
                let resolved = resolve_vars(path, nodes);
                let lua_path = to_lua_path(&resolved);
                let is_glob = lua_path.contains('*');
                source_entries.push((lua_path, is_glob));
            }
            Node::Section { name, children } => {
                if name == "windowrule" || name == "windowrulev2" {
                    let call = format_windowrule_block(name, children, nodes);
                    postamble_lines.push(call);
                } else {
                    let (section_val, extracted_keywords) = build_section_table(children, nodes);
                    set_entries.push((name.clone(), section_val));
                    for kw_call in extracted_keywords {
                        postamble_lines.push(kw_call);
                    }
                }
            }
            Node::Assignment { key, value } => {
                if key == "autogenerated" {
                    continue;
                }
                let resolved = resolve_vars(value, nodes);
                if key.contains('.') {
                    let parts: Vec<&str> = key.splitn(2, '.').collect();
                    let section = parts[0].to_string();
                    let inner_key = parts[1].to_string();
                    if let Some(existing) = set_entries.iter_mut().find(|(k, _)| k == &section) {
                        if let LuaValue::Table(ref mut entries) = existing.1 {
                            entries.push((inner_key, lua_value(&resolved)));
                        }
                    } else {
                        set_entries.push((
                            section,
                            LuaValue::Table(vec![(inner_key, lua_value(&resolved))]),
                        ));
                    }
                } else {
                    set_entries.push((key.clone(), lua_value(&resolved)));
                }
            }
            Node::Bind { variant, args } => {
                let resolved_args: Vec<String> = args.iter().map(|a| resolve_vars(a, nodes)).collect();
                let call = format_bind(variant, &resolved_args);
                postamble_lines.push(call);
            }
            Node::Keyword { name, args } => {
                let resolved_args: Vec<String> = args.iter().map(|a| resolve_vars(a, nodes)).collect();
                let call = format_keyword(name, &resolved_args);
                postamble_lines.push(call);
            }
        }
    }

    let preamble = collapse_blank_lines(&preamble_lines);
    
    if !source_entries.is_empty() {
        out.push_str("local home = os.getenv(\"HOME\")\n");
        out.push_str("local function expand_home(p)\n");
        out.push_str("  if p:sub(1, 2) == \"~/\" then\n");
        out.push_str("    return home .. p:sub(2)\n");
        out.push_str("  end\n");
        out.push_str("  return p\n");
        out.push_str("end\n\n");
        
        out.push_str("local function req(path)\n");
        out.push_str("  local expanded = expand_home(path)\n");
        out.push_str("  local dir = expanded:match(\"(.*/)\")\n");
        out.push_str("  local name = expanded:match(\"([^/]+)$\"):gsub(\"%.lua$\", \"\")\n");
        out.push_str("  local saved = package.path\n");
        out.push_str("  package.path = dir .. \"?.lua;\" .. dir .. \"?/init.lua\"\n");
        out.push_str("  package.loaded[name] = nil\n");
        out.push_str("  local mod = require(name)\n");
        out.push_str("  package.path = saved\n");
        out.push_str("  return mod\n");
        out.push_str("end\n\n");
        
        out.push_str("local function req_glob(pattern)\n");
        out.push_str("  local expanded = expand_home(pattern)\n");
        out.push_str("  local dir = expanded:match(\"(.*/)\")\n");
        out.push_str("  local handle = io.popen(\"ls -1 \" .. expanded .. \" 2>/dev/null\")\n");
        out.push_str("  if handle then\n");
        out.push_str("    for file in handle:lines() do\n");
        out.push_str("      local name = file:match(\"([^/]+)$\"):gsub(\"%.lua$\", \"\")\n");
        out.push_str("      local saved = package.path\n");
        out.push_str("      package.path = dir .. \"?.lua;\" .. dir .. \"?/init.lua\"\n");
        out.push_str("      package.loaded[name] = nil\n");
        out.push_str("      require(name)\n");
        out.push_str("      package.path = saved\n");
        out.push_str("    end\n");
        out.push_str("    handle:close()\n");
        out.push_str("  end\n");
        out.push_str("end\n\n");
        
        for (path, is_glob) in &source_entries {
            if *is_glob {
                out.push_str(&format!("req_glob({})\n", lua_string(path)));
            } else {
                out.push_str(&format!("req({})\n", lua_string(path)));
            }
        }
        out.push('\n');
    }
    
    out.push_str(&preamble);

    if !set_entries.is_empty() {
        out.push_str("\nhl.set {\n");
        for (key, val) in &set_entries {
            write_table_entry(&mut out, key, val, 1);
        }
        out.push_str("}\n");
    }

    if !postamble_lines.is_empty() {
        out.push('\n');
        for line in &postamble_lines {
            out.push_str(line);
            out.push('\n');
        }
    }

    out
}

fn collapse_blank_lines(lines: &[String]) -> String {
    let mut result = String::new();
    let mut prev_blank = false;
    for line in lines {
        if line.is_empty() {
            if !prev_blank {
                result.push('\n');
            }
            prev_blank = true;
        } else {
            result.push_str(line);
            result.push('\n');
            prev_blank = false;
        }
    }
    result
}

#[derive(Debug, Clone)]
#[allow(dead_code)]
enum LuaValue {
    Str(String),
    Num(String),
    Bool(bool),
    Table(Vec<(String, LuaValue)>),
    Raw(String),
}

fn build_section_table(children: &[Node], all_nodes: &[Node]) -> (LuaValue, Vec<String>) {
    let mut entries: Vec<(String, LuaValue)> = Vec::new();
    let mut extracted_keywords: Vec<String> = Vec::new();

    for child in children {
        match child {
            Node::Assignment { key, value } => {
                let resolved = resolve_vars(value, all_nodes);
                if key.contains('.') {
                    let parts: Vec<&str> = key.splitn(2, '.').collect();
                    let section = parts[0].to_string();
                    let inner_key = parts[1].to_string();
                    if let Some(existing) = entries.iter_mut().find(|(k, _)| k == &section) {
                        if let LuaValue::Table(ref mut inner) = existing.1 {
                            inner.push((inner_key, lua_value(&resolved)));
                        }
                    } else {
                        entries.push((
                            section,
                            LuaValue::Table(vec![(inner_key, lua_value(&resolved))]),
                        ));
                    }
                } else {
                    entries.push((key.clone(), lua_value(&resolved)));
                }
            }
            Node::Section { name, children: grandchildren } => {
                let (sub, sub_keywords) = build_section_table(grandchildren, all_nodes);
                entries.push((name.clone(), sub));
                extracted_keywords.extend(sub_keywords);
            }
            Node::Keyword { name, args } => {
                let resolved_args: Vec<String> = args.iter().map(|a| resolve_vars(a, all_nodes)).collect();
                let call = format_keyword(name, &resolved_args);
                extracted_keywords.push(call);
            }
            Node::Comment(_) | Node::BlankLine => {}
            _ => {}
        }
    }

    (LuaValue::Table(entries), extracted_keywords)
}

fn lua_value(s: &str) -> LuaValue {
    let trimmed = s.trim();

    if trimmed == "true" {
        return LuaValue::Bool(true);
    }
    if trimmed == "false" {
        return LuaValue::Bool(false);
    }

    if trimmed.parse::<i64>().is_ok() || trimmed.parse::<f64>().is_ok() {
        return LuaValue::Num(trimmed.to_string());
    }

    if trimmed.starts_with("0x") && trimmed[2..].chars().all(|c| c.is_ascii_hexdigit()) {
        return LuaValue::Num(trimmed.to_string());
    }

    if trimmed.starts_with("rgba(") || trimmed.starts_with("rgb(") {
        return LuaValue::Str(trimmed.to_string());
    }

    LuaValue::Str(trimmed.to_string())
}

fn resolve_vars(value: &str, nodes: &[Node]) -> String {
    let mut result = value.to_string();
    for node in nodes {
        if let Node::Variable { name, value: var_val } = node {
            let pattern = format!("${}", name);
            if result.contains(&pattern) {
                result = result.replace(&pattern, var_val);
            }
        }
    }
    result
}

fn to_lua_path(path: &str) -> String {
    let stripped = path
        .trim_end_matches(".conf")
        .trim_end_matches(".lua");
    format!("{}.lua", stripped)
}

fn sanitize_var_name(name: &str) -> String {
    name.replace('-', "_").replace(' ', "_")
}

fn lua_string(s: &str) -> String {
    let escaped = s.replace('\\', "\\\\").replace('"', "\\\"");
    format!("\"{}\"", escaped)
}

fn format_lua_value(val: &LuaValue) -> String {
    match val {
        LuaValue::Str(s) => lua_string(s),
        LuaValue::Num(n) => n.clone(),
        LuaValue::Bool(b) => b.to_string(),
        LuaValue::Raw(r) => r.clone(),
        LuaValue::Table(entries) => {
            let mut s = String::from("{\n");
            for (k, v) in entries {
                s.push_str(&format!("    {} = {},\n", k, format_lua_value(v)));
            }
            s.push('}');
            s
        }
    }
}

fn format_bind(variant: &str, args: &[String]) -> String {
    let hl_fn = match variant {
        "bind" => "hl.bind",
        "bindl" => "hl.bindl",
        "bindm" => "hl.bindm",
        "bindr" => "hl.bindr",
        "bindle" => "hl.bindle",
        "bindlr" => "hl.bindlr",
        "bindd" => "hl.bindd",
        "bindeld" => "hl.bindeld",
        "bindld" => "hl.bindld",
        "binddr" => "hl.binddr",
        "bindmd" => "hl.bindmd",
        _ => "hl.bind",
    };

    let lua_args: Vec<String> = args.iter().map(|a| lua_string(a)).collect();
    format!("{}({})", hl_fn, lua_args.join(", "))
}

fn format_keyword(name: &str, args: &[String]) -> String {
    let hl_fn = match name {
        "exec-once" => "hl.exec_once",
        "exec" => "hl.exec",
        "windowrule" => "hl.windowrule",
        "windowrulev2" => "hl.windowrulev2",
        "workspace" => "hl.workspace",
        "monitor" => "hl.monitor",
        "bezier" => "hl.bezier",
        "animation" => "hl.animation",
        "layerrule" => "hl.layerrule",
        "plugin" => "hl.plugin",
        "env" => "hl.env",
        "unbind" => "hl.unbind",
        _ => return format!("-- unsupported keyword: {}", name),
    };

    let lua_args: Vec<String> = args.iter().map(|a| {
        if a.parse::<f64>().is_ok() {
            a.clone()
        } else {
            lua_string(a)
        }
    }).collect();
    format!("{}({})", hl_fn, lua_args.join(", "))
}

fn format_windowrule_block(name: &str, children: &[Node], all_nodes: &[Node]) -> String {
    let mut entries: Vec<(String, LuaValue)> = Vec::new();

    for child in children {
        match child {
            Node::Assignment { key, value } => {
                let resolved = resolve_vars(value, all_nodes);
                if key.contains(':') {
                    let parts: Vec<&str> = key.splitn(2, ':').collect();
                    let group = parts[0].to_string();
                    let inner_key = parts[1].to_string();
                    if let Some(existing) = entries.iter_mut().find(|(k, _)| k == &group) {
                        if let LuaValue::Table(ref mut inner) = existing.1 {
                            inner.push((inner_key, lua_value(&resolved)));
                        }
                    } else {
                        entries.push((
                            group,
                            LuaValue::Table(vec![(inner_key, lua_value(&resolved))]),
                        ));
                    }
                } else if key.contains('.') {
                    let parts: Vec<&str> = key.splitn(2, '.').collect();
                    let section = parts[0].to_string();
                    let inner_key = parts[1].to_string();
                    if let Some(existing) = entries.iter_mut().find(|(k, _)| k == &section) {
                        if let LuaValue::Table(ref mut inner) = existing.1 {
                            inner.push((inner_key, lua_value(&resolved)));
                        }
                    } else {
                        entries.push((
                            section,
                            LuaValue::Table(vec![(inner_key, lua_value(&resolved))]),
                        ));
                    }
                } else {
                    entries.push((key.clone(), lua_value(&resolved)));
                }
            }
            Node::Comment(_) | Node::BlankLine => {}
            _ => {}
        }
    }

    let hl_fn = match name {
        "windowrule" => "hl.windowrule",
        "windowrulev2" => "hl.windowrulev2",
        _ => "hl.windowrule",
    };

    let mut s = format!("{} {{\n", hl_fn);
    for (k, v) in &entries {
        write_table_entry(&mut s, k, v, 1);
    }
    s.push_str("}\n");
    s
}

fn write_table_entry(out: &mut String, key: &str, val: &LuaValue, indent: usize) {
    let pad = "    ".repeat(indent);
    let safe_key = if needs_quoting(key) {
        format!("[\"{}\"]", key)
    } else {
        key.to_string()
    };

    match val {
        LuaValue::Table(entries) => {
            out.push_str(&format!("{}{} = {{\n", pad, safe_key));
            for (k, v) in entries {
                write_table_entry(out, k, v, indent + 1);
            }
            out.push_str(&format!("{}}},\n", pad));
        }
        LuaValue::Str(s) => {
            out.push_str(&format!("{}{} = {},\n", pad, safe_key, lua_string(s)));
        }
        LuaValue::Num(n) => {
            out.push_str(&format!("{}{} = {},\n", pad, safe_key, n));
        }
        LuaValue::Bool(b) => {
            out.push_str(&format!("{}{} = {},\n", pad, safe_key, b));
        }
        LuaValue::Raw(r) => {
            out.push_str(&format!("{}{} = {},\n", pad, safe_key, r));
        }
    }
}

fn needs_quoting(key: &str) -> bool {
    if key.is_empty() {
        return true;
    }
    let first = key.chars().next().unwrap();
    if first.is_ascii_digit() {
        return true;
    }
    key.contains('-') || key.contains(' ') || key.contains('.')
}
